#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("FrescoGifTest.Resource", IsApplication=true)]

namespace FrescoGifTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010023
			public const int actualImageResource = 2130772003;
			
			// aapt resource value: 0x7f010014
			public const int actualImageScaleType = 2130771988;
			
			// aapt resource value: 0x7f010022
			public const int actualImageUri = 2130772002;
			
			// aapt resource value: 0x7f010015
			public const int backgroundImage = 2130771989;
			
			// aapt resource value: 0x7f010009
			public const int fadeDuration = 2130771977;
			
			// aapt resource value: 0x7f01000f
			public const int failureImage = 2130771983;
			
			// aapt resource value: 0x7f010010
			public const int failureImageScaleType = 2130771984;
			
			// aapt resource value: 0x7f010007
			public const int font = 2130771975;
			
			// aapt resource value: 0x7f010000
			public const int fontProviderAuthority = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fontProviderCerts = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fontProviderFetchStrategy = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fontProviderFetchTimeout = 2130771973;
			
			// aapt resource value: 0x7f010001
			public const int fontProviderPackage = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int fontProviderQuery = 2130771970;
			
			// aapt resource value: 0x7f010006
			public const int fontStyle = 2130771974;
			
			// aapt resource value: 0x7f010008
			public const int fontWeight = 2130771976;
			
			// aapt resource value: 0x7f010016
			public const int overlayImage = 2130771990;
			
			// aapt resource value: 0x7f01000b
			public const int placeholderImage = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int placeholderImageScaleType = 2130771980;
			
			// aapt resource value: 0x7f010017
			public const int pressedStateOverlayImage = 2130771991;
			
			// aapt resource value: 0x7f010013
			public const int progressBarAutoRotateInterval = 2130771987;
			
			// aapt resource value: 0x7f010011
			public const int progressBarImage = 2130771985;
			
			// aapt resource value: 0x7f010012
			public const int progressBarImageScaleType = 2130771986;
			
			// aapt resource value: 0x7f01000d
			public const int retryImage = 2130771981;
			
			// aapt resource value: 0x7f01000e
			public const int retryImageScaleType = 2130771982;
			
			// aapt resource value: 0x7f010018
			public const int roundAsCircle = 2130771992;
			
			// aapt resource value: 0x7f01001d
			public const int roundBottomLeft = 2130771997;
			
			// aapt resource value: 0x7f01001c
			public const int roundBottomRight = 2130771996;
			
			// aapt resource value: 0x7f01001a
			public const int roundTopLeft = 2130771994;
			
			// aapt resource value: 0x7f01001b
			public const int roundTopRight = 2130771995;
			
			// aapt resource value: 0x7f01001e
			public const int roundWithOverlayColor = 2130771998;
			
			// aapt resource value: 0x7f010019
			public const int roundedCornerRadius = 2130771993;
			
			// aapt resource value: 0x7f010020
			public const int roundingBorderColor = 2130772000;
			
			// aapt resource value: 0x7f010021
			public const int roundingBorderPadding = 2130772001;
			
			// aapt resource value: 0x7f01001f
			public const int roundingBorderWidth = 2130771999;
			
			// aapt resource value: 0x7f01000a
			public const int viewAspectRatio = 2130771978;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Boolean
		{
			
			// aapt resource value: 0x7f080000
			public const int abc_action_bar_embed_tabs = 2131230720;
			
			static Boolean()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Boolean()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f050003
			public const int notification_action_color_filter = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int notification_icon_bg_color = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int notification_material_background_media_default_color = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int primary_text_default_material_dark = 2131034113;
			
			// aapt resource value: 0x7f050005
			public const int ripple_material_light = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int secondary_text_default_material_dark = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int secondary_text_default_material_light = 2131034118;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f090004
			public const int compat_button_inset_horizontal_material = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int compat_button_inset_vertical_material = 2131296261;
			
			// aapt resource value: 0x7f090006
			public const int compat_button_padding_horizontal_material = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int compat_button_padding_vertical_material = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int compat_control_corner_material = 2131296264;
			
			// aapt resource value: 0x7f090009
			public const int notification_action_icon_size = 2131296265;
			
			// aapt resource value: 0x7f09000a
			public const int notification_action_text_size = 2131296266;
			
			// aapt resource value: 0x7f09000b
			public const int notification_big_circle_margin = 2131296267;
			
			// aapt resource value: 0x7f090001
			public const int notification_content_margin_start = 2131296257;
			
			// aapt resource value: 0x7f09000c
			public const int notification_large_icon_height = 2131296268;
			
			// aapt resource value: 0x7f09000d
			public const int notification_large_icon_width = 2131296269;
			
			// aapt resource value: 0x7f090002
			public const int notification_main_column_padding_top = 2131296258;
			
			// aapt resource value: 0x7f090003
			public const int notification_media_narrow_margin = 2131296259;
			
			// aapt resource value: 0x7f09000e
			public const int notification_right_icon_size = 2131296270;
			
			// aapt resource value: 0x7f090000
			public const int notification_right_side_padding_top = 2131296256;
			
			// aapt resource value: 0x7f09000f
			public const int notification_small_icon_background_padding = 2131296271;
			
			// aapt resource value: 0x7f090010
			public const int notification_small_icon_size_as_large = 2131296272;
			
			// aapt resource value: 0x7f090011
			public const int notification_subtext_size = 2131296273;
			
			// aapt resource value: 0x7f090012
			public const int notification_top_pad = 2131296274;
			
			// aapt resource value: 0x7f090013
			public const int notification_top_pad_large_text = 2131296275;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int notification_action_background = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int notification_bg = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int notification_bg_low = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int notification_bg_low_normal = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int notification_bg_low_pressed = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int notification_bg_normal = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int notification_bg_normal_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int notification_icon_background = 2130837511;
			
			// aapt resource value: 0x7f02000c
			public const int notification_template_icon_bg = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int notification_template_icon_low_bg = 2130837517;
			
			// aapt resource value: 0x7f020008
			public const int notification_tile_bg = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int notify_panel_notification_icon_bg = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int play = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int test = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f0a001a
			public const int action0 = 2131361818;
			
			// aapt resource value: 0x7f0a0017
			public const int action_container = 2131361815;
			
			// aapt resource value: 0x7f0a001e
			public const int action_divider = 2131361822;
			
			// aapt resource value: 0x7f0a0018
			public const int action_image = 2131361816;
			
			// aapt resource value: 0x7f0a0019
			public const int action_text = 2131361817;
			
			// aapt resource value: 0x7f0a0028
			public const int actions = 2131361832;
			
			// aapt resource value: 0x7f0a0006
			public const int async = 2131361798;
			
			// aapt resource value: 0x7f0a0007
			public const int blocking = 2131361799;
			
			// aapt resource value: 0x7f0a001b
			public const int cancel_action = 2131361819;
			
			// aapt resource value: 0x7f0a000b
			public const int center = 2131361803;
			
			// aapt resource value: 0x7f0a000c
			public const int centerCrop = 2131361804;
			
			// aapt resource value: 0x7f0a000d
			public const int centerInside = 2131361805;
			
			// aapt resource value: 0x7f0a0023
			public const int chronometer = 2131361827;
			
			// aapt resource value: 0x7f0a002a
			public const int end_padder = 2131361834;
			
			// aapt resource value: 0x7f0a000e
			public const int fitBottomStart = 2131361806;
			
			// aapt resource value: 0x7f0a000f
			public const int fitCenter = 2131361807;
			
			// aapt resource value: 0x7f0a0010
			public const int fitEnd = 2131361808;
			
			// aapt resource value: 0x7f0a0011
			public const int fitStart = 2131361809;
			
			// aapt resource value: 0x7f0a0012
			public const int fitXY = 2131361810;
			
			// aapt resource value: 0x7f0a0013
			public const int focusCrop = 2131361811;
			
			// aapt resource value: 0x7f0a0008
			public const int forever = 2131361800;
			
			// aapt resource value: 0x7f0a0025
			public const int icon = 2131361829;
			
			// aapt resource value: 0x7f0a0029
			public const int icon_group = 2131361833;
			
			// aapt resource value: 0x7f0a0015
			public const int img = 2131361813;
			
			// aapt resource value: 0x7f0a0016
			public const int imge = 2131361814;
			
			// aapt resource value: 0x7f0a0024
			public const int info = 2131361828;
			
			// aapt resource value: 0x7f0a0009
			public const int italic = 2131361801;
			
			// aapt resource value: 0x7f0a0000
			public const int line1 = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int line3 = 2131361793;
			
			// aapt resource value: 0x7f0a001d
			public const int media_actions = 2131361821;
			
			// aapt resource value: 0x7f0a0014
			public const int none = 2131361812;
			
			// aapt resource value: 0x7f0a000a
			public const int normal = 2131361802;
			
			// aapt resource value: 0x7f0a0027
			public const int notification_background = 2131361831;
			
			// aapt resource value: 0x7f0a0020
			public const int notification_main_column = 2131361824;
			
			// aapt resource value: 0x7f0a001f
			public const int notification_main_column_container = 2131361823;
			
			// aapt resource value: 0x7f0a0026
			public const int right_icon = 2131361830;
			
			// aapt resource value: 0x7f0a0021
			public const int right_side = 2131361825;
			
			// aapt resource value: 0x7f0a001c
			public const int status_bar_latest_event_content = 2131361820;
			
			// aapt resource value: 0x7f0a0002
			public const int tag_transition_group = 2131361794;
			
			// aapt resource value: 0x7f0a0003
			public const int text = 2131361795;
			
			// aapt resource value: 0x7f0a0004
			public const int text2 = 2131361796;
			
			// aapt resource value: 0x7f0a0022
			public const int time = 2131361826;
			
			// aapt resource value: 0x7f0a0005
			public const int title = 2131361797;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f060000
			public const int cancel_button_image_alpha = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int status_bar_notification_info_maxnum = 2131099649;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int notification_action = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int notification_action_tombstone = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int notification_media_action = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int notification_media_cancel_action = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int notification_template_big_media = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int notification_template_big_media_custom = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int notification_template_big_media_narrow = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int notification_template_big_media_narrow_custom = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int notification_template_custom_big = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int notification_template_icon_group = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int notification_template_lines_media = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int notification_template_media = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int notification_template_media_custom = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int notification_template_part_chronometer = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int notification_template_part_time = 2130903055;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f070001
			public const int app_name = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int status_bar_notification_info_overflow = 2131165184;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040005
			public const int TextAppearance_Compat_Notification = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int TextAppearance_Compat_Notification_Info = 2130968582;
			
			// aapt resource value: 0x7f040000
			public const int TextAppearance_Compat_Notification_Info_Media = 2130968576;
			
			// aapt resource value: 0x7f04000b
			public const int TextAppearance_Compat_Notification_Line2 = 2130968587;
			
			// aapt resource value: 0x7f040004
			public const int TextAppearance_Compat_Notification_Line2_Media = 2130968580;
			
			// aapt resource value: 0x7f040001
			public const int TextAppearance_Compat_Notification_Media = 2130968577;
			
			// aapt resource value: 0x7f040007
			public const int TextAppearance_Compat_Notification_Time = 2130968583;
			
			// aapt resource value: 0x7f040002
			public const int TextAppearance_Compat_Notification_Time_Media = 2130968578;
			
			// aapt resource value: 0x7f040008
			public const int TextAppearance_Compat_Notification_Title = 2130968584;
			
			// aapt resource value: 0x7f040003
			public const int TextAppearance_Compat_Notification_Title_Media = 2130968579;
			
			// aapt resource value: 0x7f040009
			public const int Widget_Compat_NotificationActionContainer = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int Widget_Compat_NotificationActionText = 2130968586;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FontFamily = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 0
			public const int FontFamily_fontProviderAuthority = 0;
			
			// aapt resource value: 3
			public const int FontFamily_fontProviderCerts = 3;
			
			// aapt resource value: 4
			public const int FontFamily_fontProviderFetchStrategy = 4;
			
			// aapt resource value: 5
			public const int FontFamily_fontProviderFetchTimeout = 5;
			
			// aapt resource value: 1
			public const int FontFamily_fontProviderPackage = 1;
			
			// aapt resource value: 2
			public const int FontFamily_fontProviderQuery = 2;
			
			public static int[] FontFamilyFont = new int[] {
					16844082,
					16844083,
					16844095,
					2130771974,
					2130771975,
					2130771976};
			
			// aapt resource value: 0
			public const int FontFamilyFont_android_font = 0;
			
			// aapt resource value: 2
			public const int FontFamilyFont_android_fontStyle = 2;
			
			// aapt resource value: 1
			public const int FontFamilyFont_android_fontWeight = 1;
			
			// aapt resource value: 4
			public const int FontFamilyFont_font = 4;
			
			// aapt resource value: 3
			public const int FontFamilyFont_fontStyle = 3;
			
			// aapt resource value: 5
			public const int FontFamilyFont_fontWeight = 5;
			
			public static int[] GenericDraweeHierarchy = new int[] {
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001};
			
			// aapt resource value: 11
			public const int GenericDraweeHierarchy_actualImageScaleType = 11;
			
			// aapt resource value: 12
			public const int GenericDraweeHierarchy_backgroundImage = 12;
			
			// aapt resource value: 0
			public const int GenericDraweeHierarchy_fadeDuration = 0;
			
			// aapt resource value: 6
			public const int GenericDraweeHierarchy_failureImage = 6;
			
			// aapt resource value: 7
			public const int GenericDraweeHierarchy_failureImageScaleType = 7;
			
			// aapt resource value: 13
			public const int GenericDraweeHierarchy_overlayImage = 13;
			
			// aapt resource value: 2
			public const int GenericDraweeHierarchy_placeholderImage = 2;
			
			// aapt resource value: 3
			public const int GenericDraweeHierarchy_placeholderImageScaleType = 3;
			
			// aapt resource value: 14
			public const int GenericDraweeHierarchy_pressedStateOverlayImage = 14;
			
			// aapt resource value: 10
			public const int GenericDraweeHierarchy_progressBarAutoRotateInterval = 10;
			
			// aapt resource value: 8
			public const int GenericDraweeHierarchy_progressBarImage = 8;
			
			// aapt resource value: 9
			public const int GenericDraweeHierarchy_progressBarImageScaleType = 9;
			
			// aapt resource value: 4
			public const int GenericDraweeHierarchy_retryImage = 4;
			
			// aapt resource value: 5
			public const int GenericDraweeHierarchy_retryImageScaleType = 5;
			
			// aapt resource value: 15
			public const int GenericDraweeHierarchy_roundAsCircle = 15;
			
			// aapt resource value: 20
			public const int GenericDraweeHierarchy_roundBottomLeft = 20;
			
			// aapt resource value: 19
			public const int GenericDraweeHierarchy_roundBottomRight = 19;
			
			// aapt resource value: 17
			public const int GenericDraweeHierarchy_roundTopLeft = 17;
			
			// aapt resource value: 18
			public const int GenericDraweeHierarchy_roundTopRight = 18;
			
			// aapt resource value: 21
			public const int GenericDraweeHierarchy_roundWithOverlayColor = 21;
			
			// aapt resource value: 16
			public const int GenericDraweeHierarchy_roundedCornerRadius = 16;
			
			// aapt resource value: 23
			public const int GenericDraweeHierarchy_roundingBorderColor = 23;
			
			// aapt resource value: 24
			public const int GenericDraweeHierarchy_roundingBorderPadding = 24;
			
			// aapt resource value: 22
			public const int GenericDraweeHierarchy_roundingBorderWidth = 22;
			
			// aapt resource value: 1
			public const int GenericDraweeHierarchy_viewAspectRatio = 1;
			
			public static int[] SimpleDraweeView = new int[] {
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982,
					2130771983,
					2130771984,
					2130771985,
					2130771986,
					2130771987,
					2130771988,
					2130771989,
					2130771990,
					2130771991,
					2130771992,
					2130771993,
					2130771994,
					2130771995,
					2130771996,
					2130771997,
					2130771998,
					2130771999,
					2130772000,
					2130772001,
					2130772002,
					2130772003};
			
			// aapt resource value: 26
			public const int SimpleDraweeView_actualImageResource = 26;
			
			// aapt resource value: 11
			public const int SimpleDraweeView_actualImageScaleType = 11;
			
			// aapt resource value: 25
			public const int SimpleDraweeView_actualImageUri = 25;
			
			// aapt resource value: 12
			public const int SimpleDraweeView_backgroundImage = 12;
			
			// aapt resource value: 0
			public const int SimpleDraweeView_fadeDuration = 0;
			
			// aapt resource value: 6
			public const int SimpleDraweeView_failureImage = 6;
			
			// aapt resource value: 7
			public const int SimpleDraweeView_failureImageScaleType = 7;
			
			// aapt resource value: 13
			public const int SimpleDraweeView_overlayImage = 13;
			
			// aapt resource value: 2
			public const int SimpleDraweeView_placeholderImage = 2;
			
			// aapt resource value: 3
			public const int SimpleDraweeView_placeholderImageScaleType = 3;
			
			// aapt resource value: 14
			public const int SimpleDraweeView_pressedStateOverlayImage = 14;
			
			// aapt resource value: 10
			public const int SimpleDraweeView_progressBarAutoRotateInterval = 10;
			
			// aapt resource value: 8
			public const int SimpleDraweeView_progressBarImage = 8;
			
			// aapt resource value: 9
			public const int SimpleDraweeView_progressBarImageScaleType = 9;
			
			// aapt resource value: 4
			public const int SimpleDraweeView_retryImage = 4;
			
			// aapt resource value: 5
			public const int SimpleDraweeView_retryImageScaleType = 5;
			
			// aapt resource value: 15
			public const int SimpleDraweeView_roundAsCircle = 15;
			
			// aapt resource value: 20
			public const int SimpleDraweeView_roundBottomLeft = 20;
			
			// aapt resource value: 19
			public const int SimpleDraweeView_roundBottomRight = 19;
			
			// aapt resource value: 17
			public const int SimpleDraweeView_roundTopLeft = 17;
			
			// aapt resource value: 18
			public const int SimpleDraweeView_roundTopRight = 18;
			
			// aapt resource value: 21
			public const int SimpleDraweeView_roundWithOverlayColor = 21;
			
			// aapt resource value: 16
			public const int SimpleDraweeView_roundedCornerRadius = 16;
			
			// aapt resource value: 23
			public const int SimpleDraweeView_roundingBorderColor = 23;
			
			// aapt resource value: 24
			public const int SimpleDraweeView_roundingBorderPadding = 24;
			
			// aapt resource value: 22
			public const int SimpleDraweeView_roundingBorderWidth = 22;
			
			// aapt resource value: 1
			public const int SimpleDraweeView_viewAspectRatio = 1;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
